slogo_team08: application.Turtle Class Reference
application.Turtle Class Reference
Public Member Functions
Turtle ()
DoubleProperty getHeadingProperty ()
double getHeading ()
void setHeading (double heading)
Property< double[]> getLocationProperty ()
double[] getLocation ()
double getX ()
double getY ()
double setLocation (double x, double y)
BooleanProperty getPenDownProperty ()
boolean isPenDown ()
void setPenDown (boolean penDown)
BooleanProperty getShowingProperty ()
boolean isShowing ()
void setShowing (boolean showing)
DoubleProperty shapeProperty ()
BooleanProperty stampProperty ()
Node getNode ()
void setNode (Node node)
Static Public Member Functions
static double getFullRotation ()
static double getHalfRotation ()
Private Attributes
DoubleProperty heading = new SimpleDoubleProperty()
ObjectProperty< double[]> location = new SimpleObjectProperty<>()
BooleanProperty penDown = new SimpleBooleanProperty()
BooleanProperty showing = new SimpleBooleanProperty()
BooleanProperty stamp = new SimpleBooleanProperty()
DoubleProperty shape = new SimpleDoubleProperty()
ObjectProperty< Node > node = new SimpleObjectProperty<>()
Static Private Attributes
static final double FULL_ROTATION = 360
static final double HALF_ROTATION = 180
Detailed Description
Definition at line 12 of file Turtle.java.
Constructor & Destructor Documentation
application.Turtle.Turtle ()
Definition at line 23 of file Turtle.java.
Member Function Documentation
static double application.Turtle.getFullRotation () static
Definition at line 31 of file Turtle.java.
References application.Turtle.FULL_ROTATION.
Referenced by commands.Left.function(), commands.Right.function(), commands.SetHeading.function(), and commands.SetTowards.getOffset().
static double application.Turtle.getHalfRotation () static
Definition at line 35 of file Turtle.java.
References application.Turtle.HALF_ROTATION.
Referenced by commands.SetTowards.getOffset().
double application.Turtle.getHeading ()
Definition at line 43 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
DoubleProperty application.Turtle.getHeadingProperty ()
Definition at line 39 of file Turtle.java.
References application.Turtle.heading.
Referenced by view.View.addTurtleListeners().
double [] application.Turtle.getLocation ()
Definition at line 55 of file Turtle.java.
Property<double[]> application.Turtle.getLocationProperty ()
Definition at line 51 of file Turtle.java.
References application.Turtle.location.
Referenced by view.View.addTurtleListeners().
Node application.Turtle.getNode ()
Definition at line 106 of file Turtle.java.
BooleanProperty application.Turtle.getPenDownProperty ()
Definition at line 74 of file Turtle.java.
References application.Turtle.penDown.
Referenced by view.View.addTurtleListeners().
BooleanProperty application.Turtle.getShowingProperty ()
Definition at line 86 of file Turtle.java.
References application.Turtle.showing.
Referenced by view.View.addTurtleListeners().
double application.Turtle.getX ()
Definition at line 59 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
double application.Turtle.getY ()
Definition at line 63 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
boolean application.Turtle.isPenDown ()
Definition at line 78 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
boolean application.Turtle.isShowing ()
Definition at line 90 of file Turtle.java.
void application.Turtle.setHeading (double heading)
Definition at line 47 of file Turtle.java.
double application.Turtle.setLocation (double x, double y)
Definition at line 67 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
void application.Turtle.setNode (Node node)
Definition at line 110 of file Turtle.java.
void application.Turtle.setPenDown (boolean penDown)
Definition at line 82 of file Turtle.java.
Referenced by commands.Forward.advanceTurtle().
void application.Turtle.setShowing (boolean showing)
Definition at line 94 of file Turtle.java.
DoubleProperty application.Turtle.shapeProperty ()
Definition at line 98 of file Turtle.java.
References application.Turtle.shape.
Referenced by view.View.addTurtleListeners().
BooleanProperty application.Turtle.stampProperty ()
Definition at line 102 of file Turtle.java.
References application.Turtle.stamp.
Member Data Documentation
final double application.Turtle.FULL_ROTATION = 360 static private
Definition at line 13 of file Turtle.java.
Referenced by application.Turtle.getFullRotation().
final double application.Turtle.HALF_ROTATION = 180 static private
Definition at line 14 of file Turtle.java.
Referenced by application.Turtle.getHalfRotation().
DoubleProperty application.Turtle.heading = new SimpleDoubleProperty() private
Definition at line 15 of file Turtle.java.
Referenced by application.Turtle.getHeadingProperty().
ObjectProperty<double[]> application.Turtle.location = new SimpleObjectProperty<>() private
Definition at line 16 of file Turtle.java.
Referenced by application.Turtle.getLocationProperty().
ObjectProperty<Node> application.Turtle.node = new SimpleObjectProperty<>() private
Definition at line 21 of file Turtle.java.
BooleanProperty application.Turtle.penDown = new SimpleBooleanProperty() private
Definition at line 17 of file Turtle.java.
Referenced by application.Turtle.getPenDownProperty().
DoubleProperty application.Turtle.shape = new SimpleDoubleProperty() private
Definition at line 20 of file Turtle.java.
Referenced by application.Turtle.shapeProperty().
BooleanProperty application.Turtle.showing = new SimpleBooleanProperty() private
Definition at line 18 of file Turtle.java.
Referenced by application.Turtle.getShowingProperty().
BooleanProperty application.Turtle.stamp = new SimpleBooleanProperty() private
Definition at line 19 of file Turtle.java.
Referenced by application.Turtle.stampProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/application/Turtle.java