slogo_team08: view.TurtleState Class Reference
view.TurtleState Class Reference
Public Member Functions
TurtleState (TurtleList t)
Protected Member Functions
Button state ()
Button refreshButton ()
void attrib ()
void refresh ()
void StateOfTurtle ()
Package Attributes
TurtleList tList = new TurtleList()
Private Member Functions
GridPane output ()
Private Attributes
Stage t = new Stage()
Label turtleX = new Label("TurtleX")
Label turtleY = new Label("TurtleY")
Label rotation = new Label("Rotation")
Label pen = new Label("Pen Down?")
ArrayList< Double > x = new ArrayList<Double>()
ArrayList< Double > y = new ArrayList<Double>()
ArrayList< Double > r = new ArrayList<Double>()
ArrayList< Boolean > isPen = new ArrayList<Boolean>()
Detailed Description
Definition at line 15 of file TurtleState.java.
Constructor & Destructor Documentation
view.TurtleState.TurtleState (TurtleList t)
Definition at line 18 of file TurtleState.java.
References view.TurtleState.t.
Member Function Documentation
void view.TurtleState.attrib () protected
Definition at line 49 of file TurtleState.java.
References application.TurtleList.getActiveTurtles().
Referenced by view.TurtleState.state().
GridPane view.TurtleState.output () private
Definition at line 71 of file TurtleState.java.
Referenced by view.TurtleState.StateOfTurtle().
void view.TurtleState.refresh () protected
Definition at line 62 of file TurtleState.java.
Referenced by view.TurtleState.refreshButton().
Button view.TurtleState.refreshButton () protected
Definition at line 42 of file TurtleState.java.
References view.TurtleState.refresh().
Referenced by view.TurtleState.StateOfTurtle().
Button view.TurtleState.state () protected
Definition at line 33 of file TurtleState.java.
References view.TurtleState.attrib(), and view.TurtleState.StateOfTurtle().
Referenced by view.View.start().
void view.TurtleState.StateOfTurtle () protected
Definition at line 85 of file TurtleState.java.
References view.TurtleState.output(), and view.TurtleState.refreshButton().
Referenced by view.TurtleState.state().
Member Data Documentation
ArrayList<Boolean> view.TurtleState.isPen = new ArrayList<Boolean>() private
Definition at line 30 of file TurtleState.java.
Label view.TurtleState.pen = new Label("Pen Down?") private
Definition at line 26 of file TurtleState.java.
ArrayList<Double> view.TurtleState.r = new ArrayList<Double>() private
Definition at line 29 of file TurtleState.java.
Label view.TurtleState.rotation = new Label("Rotation") private
Definition at line 25 of file TurtleState.java.
Stage view.TurtleState.t = new Stage() private
Definition at line 21 of file TurtleState.java.
Referenced by view.TurtleState.TurtleState().
TurtleList view.TurtleState.tList = new TurtleList() package
Definition at line 17 of file TurtleState.java.
Label view.TurtleState.turtleX = new Label("TurtleX") private
Definition at line 23 of file TurtleState.java.
Label view.TurtleState.turtleY = new Label("TurtleY") private
Definition at line 24 of file TurtleState.java.
ArrayList<Double> view.TurtleState.x = new ArrayList<Double>() private
Definition at line 27 of file TurtleState.java.
ArrayList<Double> view.TurtleState.y = new ArrayList<Double>() private
Definition at line 28 of file TurtleState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/TurtleState.java