slogo_team08: application.Model Class Reference
application.Model Class Reference
Public Member Functions
Model (double maxX, double maxY)
void updateCommandPatterns ()
TurtleList getTurtleList ()
void setLanguage (String language)
String getLanguage ()
double getMaxX ()
double getMaxY ()
Double getVariableValue (String key)
void setVariableValue (String key, double value)
void removeVariableValue (String key)
void addUserCommand (String key, EvaluatorNode value)
CommandNode getUserCommand (String key)
StringProperty errorMessageProperty ()
DoubleProperty backgroundProperty ()
DoubleProperty penSizeProperty ()
DoubleProperty penColorProperty ()
ObjectProperty< double[]> palletProperty ()
BooleanProperty clearScreenProperty ()
BooleanProperty clearStampProperty ()
void update (Observable arg0, Object arg1)
Private Attributes
Parser myParser
TurtleList myTurtleList
Map< String, CommandNode > myUserCommands
Map< String, CommandNode > myCommandHistory
Map< String, Double > variableMap
double maxX
double maxY
String myLanguage
StringProperty errorMsg = new SimpleStringProperty()
DoubleProperty background = new SimpleDoubleProperty()
DoubleProperty penSize = new SimpleDoubleProperty()
DoubleProperty penColor = new SimpleDoubleProperty()
ObjectProperty< double[]> pallet = new SimpleObjectProperty<>()
BooleanProperty clearScreen = new SimpleBooleanProperty()
BooleanProperty clearStamp = new SimpleBooleanProperty()
Detailed Description
Definition at line 22 of file Model.java.
Constructor & Destructor Documentation
application.Model.Model (double maxX, double maxY)
Definition at line 39 of file Model.java.
References application.Model.maxX, and application.Model.maxY.
Member Function Documentation
void application.Model.addUserCommand (String key, EvaluatorNode value)
Definition at line 87 of file Model.java.
Referenced by commands.MakeUserInstruction.function().
DoubleProperty application.Model.backgroundProperty ()
Definition at line 99 of file Model.java.
References application.Model.background.
Referenced by view.View.addModelListeners(), and commands.SetBackground.function().
BooleanProperty application.Model.clearScreenProperty ()
Definition at line 115 of file Model.java.
References application.Model.clearScreen.
Referenced by view.View.addModelListeners(), and commands.ClearScreen.function().
BooleanProperty application.Model.clearStampProperty ()
Definition at line 119 of file Model.java.
References application.Model.clearStamp.
Referenced by view.View.addModelListeners(), and commands.ClearStamp.function().
StringProperty application.Model.errorMessageProperty ()
Definition at line 95 of file Model.java.
References application.Model.errorMsg.
Referenced by view.View.addModelListeners().
String application.Model.getLanguage ()
Definition at line 63 of file Model.java.
References application.Model.myLanguage.
Referenced by application.Parser.Parser(), and application.Parser.updateCommandPatterns().
double application.Model.getMaxX ()
Definition at line 67 of file Model.java.
References application.Model.maxX.
Referenced by commands.Forward.advanceTurtle().
double application.Model.getMaxY ()
Definition at line 71 of file Model.java.
References application.Model.maxY.
Referenced by commands.Forward.advanceTurtle().
TurtleList application.Model.getTurtleList ()
Definition at line 54 of file Model.java.
References application.Model.myTurtleList.
Referenced by view.View.addModelListeners(), tree.CommandNode.evaluate(), commands.Tell.function(), commands.Ask.function(), and view.View.start().
CommandNode application.Model.getUserCommand (String key)
Definition at line 91 of file Model.java.
Referenced by syntax.CommandHandler.handle().
Double application.Model.getVariableValue (String key)
Definition at line 75 of file Model.java.
Referenced by tree.VariableNode.evaluate().
ObjectProperty<double[]> application.Model.palletProperty ()
Definition at line 111 of file Model.java.
References application.Model.pallet.
Referenced by view.View.addModelListeners(), and commands.SetPallet.function().
DoubleProperty application.Model.penColorProperty ()
Definition at line 107 of file Model.java.
References application.Model.penColor.
Referenced by view.View.addModelListeners(), and commands.SetPenColor.function().
DoubleProperty application.Model.penSizeProperty ()
Definition at line 103 of file Model.java.
References application.Model.penSize.
Referenced by view.View.addModelListeners(), and commands.SetPenSize.function().
void application.Model.removeVariableValue (String key)
Definition at line 83 of file Model.java.
Referenced by commands.DoTimes.runForLoop().
void application.Model.setLanguage (String language)
Definition at line 58 of file Model.java.
Referenced by view.View.addModelListeners(), and view.LanguageChooser.setLanguage().
void application.Model.setVariableValue (String key, double value)
Definition at line 79 of file Model.java.
Referenced by commands.MakeVariable.function(), and commands.DoTimes.runForLoop().
void application.Model.update (Observable arg0, Object arg1)
Definition at line 124 of file Model.java.
References tree.CommandNode.evaluate(), and application.Parser.parse().
void application.Model.updateCommandPatterns ()
Definition at line 50 of file Model.java.
References application.Parser.updateCommandPatterns().
Referenced by view.View.addModelListeners().
Member Data Documentation
DoubleProperty application.Model.background = new SimpleDoubleProperty() private
Definition at line 32 of file Model.java.
Referenced by application.Model.backgroundProperty().
BooleanProperty application.Model.clearScreen = new SimpleBooleanProperty() private
Definition at line 36 of file Model.java.
Referenced by application.Model.clearScreenProperty().
BooleanProperty application.Model.clearStamp = new SimpleBooleanProperty() private
Definition at line 37 of file Model.java.
Referenced by application.Model.clearStampProperty().
StringProperty application.Model.errorMsg = new SimpleStringProperty() private
Definition at line 31 of file Model.java.
Referenced by application.Model.errorMessageProperty().
double application.Model.maxX private
Definition at line 28 of file Model.java.
Referenced by application.Model.getMaxX(), and application.Model.Model().
double application.Model.maxY private
Definition at line 29 of file Model.java.
Referenced by application.Model.getMaxY(), and application.Model.Model().
Map<String, CommandNode> application.Model.myCommandHistory private
Definition at line 26 of file Model.java.
String application.Model.myLanguage private
Definition at line 30 of file Model.java.
Referenced by application.Model.getLanguage().
Parser application.Model.myParser private
Definition at line 23 of file Model.java.
TurtleList application.Model.myTurtleList private
Definition at line 24 of file Model.java.
Referenced by application.Model.getTurtleList().
Map<String, CommandNode> application.Model.myUserCommands private
Definition at line 25 of file Model.java.
ObjectProperty<double[]> application.Model.pallet = new SimpleObjectProperty<>() private
Definition at line 35 of file Model.java.
Referenced by application.Model.palletProperty().
DoubleProperty application.Model.penColor = new SimpleDoubleProperty() private
Definition at line 34 of file Model.java.
Referenced by application.Model.penColorProperty().
DoubleProperty application.Model.penSize = new SimpleDoubleProperty() private
Definition at line 33 of file Model.java.
Referenced by application.Model.penSizeProperty().
Map<String, Double> application.Model.variableMap private
Definition at line 27 of file Model.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/application/Model.java