slogo_team08: view.View Class Reference
view.View Class Reference
Public Member Functions
View (Model myModel)
void start (Stage stage)
void addModelListeners (Model model)
void addTurtleListeners (Turtle t)
void displayError (String s)
Static Public Attributes
static final Integer[] SIZE_OF_WINDOW ={800,800}
static final Integer[] SIZE_OF_TURTLE_DISPLAY ={375,375}
static final Integer[] LOCATION_OF_ENTERCOMMANDS_BOX ={100,500}
static final Integer[] LOCATION_OF_PREVIOUSCOMMANDS_BOX ={590,100}
static final Integer[] LOCATION_OF_BUTTONBAR ={675,550}
static final Integer[] LOCATION_OF_COMMANDGUIDE ={0,500}
Protected Member Functions
void addToRoot (Node n)
LanguageChooser getLang ()
Model getModel ()
Private Attributes
Display display =new Display()
LanguageChooser lang
ColorChooser col
ButtonBar myButtonBar
PreviousCommands prev =new PreviousCommands()
EnterCommands enter =new EnterCommands(prev)
CommandGuide comm =new CommandGuide()
ImportDesign des = new ImportDesign(enter)
CreateDesign cre = new CreateDesign(enter)
Group root
Model m
TurtleState tState
ImageChooser img
Detailed Description
Definition at line 21 of file View.java.
Constructor & Destructor Documentation
view.View.View (Model myModel)
Definition at line 43 of file View.java.
References view.ColorChooser.getDisplay().
Member Function Documentation
void view.View.addModelListeners (Model model)
Definition at line 97 of file View.java.
References view.Display.addToRoot(), view.Display.addTurtle(), view.View.addTurtleListeners(), application.Model.backgroundProperty(), application.Model.clearScreenProperty(), application.Model.clearStampProperty(), view.View.displayError(), application.Model.errorMessageProperty(), view.Display.getMap(), view.Display.getRoot(), view.LanguageChooser.getStringProperty(), application.TurtleList.getTurtle(), application.Model.getTurtleList(), application.TurtleList.IDProperty(), view.Display.makeDisplay(), application.Model.palletProperty(), application.Model.penColorProperty(), application.Model.penSizeProperty(), application.Model.setLanguage(), application.Model.updateCommandPatterns(), and view.Display.updateMap().
Referenced by application.Wrapper.makeNewWindow().
void view.View.addToRoot (Node n) protected
Definition at line 91 of file View.java.
void view.View.addTurtleListeners (Turtle t)
Definition at line 170 of file View.java.
References application.Turtle.getHeadingProperty(), application.Turtle.getLocationProperty(), application.Turtle.getPenDownProperty(), application.Turtle.getShowingProperty(), view.Display.setVisibility(), application.Turtle.shapeProperty(), view.Display.updateTurtleHeading(), view.Display.updateTurtleLocation(), and view.Display.updateTurtleShowing().
Referenced by view.View.addModelListeners().
void view.View.displayError (String s)
Definition at line 214 of file View.java.
References view.ErrorDisplay.display().
Referenced by view.View.addModelListeners().
LanguageChooser view.View.getLang () protected
Definition at line 94 of file View.java.
References view.View.lang.
Model view.View.getModel () protected
Definition at line 211 of file View.java.
References view.View.m.
Referenced by view.LanguageChooser.setLanguage().
void view.View.start (Stage stage)
Definition at line 53 of file View.java.
References view.ButtonBar.addtoHButtonBar(), view.ButtonBar.addtoVButtonBar(), view.ImportDesign.chooseDesign(), view.PreviousCommands.getTextArea(), application.TurtleList.getTurtle(), application.Model.getTurtleList(), view.EnterCommands.init(), view.TurtleState.initiateState(), view.ButtonBar.makeButton(), view.ColorChooser.makeColorChooserPopUp(), view.Display.makeDisplay(), view.ButtonBar.makeHButtonBar(), view.ButtonBar.makeVButtonBar(), view.CommandGuide.openCommandGuide(), view.CreateDesign.saveFile(), view.LanguageChooser.setLanguage(), and view.ImageChooser.start().
Referenced by application.Wrapper.makeNewWindow().
Member Data Documentation
ColorChooser view.View.col private
Definition at line 30 of file View.java.
CommandGuide view.View.comm =new CommandGuide() private
Definition at line 34 of file View.java.
CreateDesign view.View.cre = new CreateDesign(enter) private
Definition at line 36 of file View.java.
ImportDesign view.View.des = new ImportDesign(enter) private
Definition at line 35 of file View.java.
Display view.View.display =new Display() private
Definition at line 28 of file View.java.
EnterCommands view.View.enter =new EnterCommands(prev) private
Definition at line 33 of file View.java.
ImageChooser view.View.img private
Definition at line 40 of file View.java.
LanguageChooser view.View.lang private
Definition at line 29 of file View.java.
Referenced by view.View.getLang().
final Integer [] view.View.LOCATION_OF_BUTTONBAR ={675,550} static
Definition at line 26 of file View.java.
final Integer [] view.View.LOCATION_OF_COMMANDGUIDE ={0,500} static
Definition at line 27 of file View.java.
final Integer [] view.View.LOCATION_OF_ENTERCOMMANDS_BOX ={100,500} static
Definition at line 24 of file View.java.
final Integer [] view.View.LOCATION_OF_PREVIOUSCOMMANDS_BOX ={590,100} static
Definition at line 25 of file View.java.
Model view.View.m private
Definition at line 38 of file View.java.
Referenced by view.View.getModel().
ButtonBar view.View.myButtonBar private
Definition at line 31 of file View.java.
PreviousCommands view.View.prev =new PreviousCommands() private
Definition at line 32 of file View.java.
Group view.View.root private
Definition at line 37 of file View.java.
final Integer [] view.View.SIZE_OF_TURTLE_DISPLAY ={375,375} static
Definition at line 23 of file View.java.
final Integer [] view.View.SIZE_OF_WINDOW ={800,800} static
Definition at line 22 of file View.java.
TurtleState view.View.tState private
Definition at line 39 of file View.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/View.java