slogo_team08: view.ButtonBar Class Reference
view.ButtonBar Class Reference
Public Member Functions
ButtonBar (ColorChooser c, LanguageChooser l)
Protected Member Functions
Button makeButton (String name, EventHandler< ActionEvent > myMethod, int x, int y)
VBox makeVButtonBar (int size, int x, int y)
HBox makeHButtonBar (int size, int x, int y)
void addtoVButtonBar (VBox myVBox, Control...controls)
void addtoHButtonBar (HBox myHBox, Control...controls)
Private Attributes
ColorChooser colz
ImageChooser img
LanguageChooser lang
Detailed Description
Definition at line 15 of file ButtonBar.java.
Constructor & Destructor Documentation
view.ButtonBar.ButtonBar (ColorChooser c, LanguageChooser l)
Definition at line 20 of file ButtonBar.java.
References view.ColorChooser.getDisplay().
Member Function Documentation
void view.ButtonBar.addtoHButtonBar (HBox myHBox, Control... controls) protected
Definition at line 52 of file ButtonBar.java.
Referenced by view.View.start().
void view.ButtonBar.addtoVButtonBar (VBox myVBox, Control... controls) protected
Definition at line 48 of file ButtonBar.java.
Referenced by view.View.start().
Button view.ButtonBar.makeButton (String name, EventHandler< ActionEvent > myMethod, int x, int y) protected
Definition at line 26 of file ButtonBar.java.
Referenced by view.View.start().
HBox view.ButtonBar.makeHButtonBar (int size, int x, int y) protected
Definition at line 41 of file ButtonBar.java.
Referenced by view.View.start().
VBox view.ButtonBar.makeVButtonBar (int size, int x, int y) protected
Definition at line 34 of file ButtonBar.java.
Referenced by view.View.start().
Member Data Documentation
ColorChooser view.ButtonBar.colz private
Definition at line 16 of file ButtonBar.java.
ImageChooser view.ButtonBar.img private
Definition at line 17 of file ButtonBar.java.
LanguageChooser view.ButtonBar.lang private
Definition at line 18 of file ButtonBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/ButtonBar.java