slogo_team08: view.ErrorDisplay Class Reference
view.ErrorDisplay Class Reference
Public Member Functions
Scene display (String s)
VBox message (String s, Button...buttons)
void QuitError ()
Detailed Description
Definition at line 23 of file ErrorDisplay.java.
Member Function Documentation
Scene view.ErrorDisplay.display (String s)
Definition at line 25 of file ErrorDisplay.java.
Referenced by view.View.displayError().
VBox view.ErrorDisplay.message (String s, Button... buttons)
Definition at line 42 of file ErrorDisplay.java.
Referenced by view.ErrorDisplay.QuitError().
void view.ErrorDisplay.QuitError ()
Definition at line 61 of file ErrorDisplay.java.
References view.ErrorDisplay.message().
Referenced by view.ImportDesign.chooseDesign(), and view.CreateDesign.saveFile().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/ErrorDisplay.java