slogo_team08: tree.VariableNode Class Reference
tree.VariableNode Class Reference
Public Member Functions
VariableNode (Model myModel, String myString)
List< Object > evaluate (Turtle myTurtle, List< Object > args)
int countVariables ()
List< VariableNode > getVariableNodes ()
void setIndex (int i)
Public Member Functions inherited from tree.TreeNode
abstract List< Object > evaluate (Turtle myTurtle, List< Object > args)
List< Object > evaluate ()
abstract int countVariables ()
abstract List< VariableNode > getVariableNodes ()
Private Attributes
String myString
Model myModel
Integer myIndex
Detailed Description
Definition at line 9 of file VariableNode.java.
Constructor & Destructor Documentation
tree.VariableNode.VariableNode (Model myModel, String myString)
Definition at line 15 of file VariableNode.java.
References tree.VariableNode.myModel, and tree.VariableNode.myString.
Member Function Documentation
int tree.VariableNode.countVariables ()
Definition at line 40 of file VariableNode.java.
List<Object> tree.VariableNode.evaluate (Turtle myTurtle, List< Object > args)
Definition at line 21 of file VariableNode.java.
References application.Model.getVariableValue().
Referenced by commands.MakeUserInstruction.function().
List<VariableNode> tree.VariableNode.getVariableNodes ()
Definition at line 48 of file VariableNode.java.
void tree.VariableNode.setIndex (int i)
Definition at line 54 of file VariableNode.java.
Referenced by commands.MakeUserInstruction.function().
Member Data Documentation
Integer tree.VariableNode.myIndex private
Definition at line 13 of file VariableNode.java.
Model tree.VariableNode.myModel private
Definition at line 12 of file VariableNode.java.
Referenced by tree.VariableNode.VariableNode().
String tree.VariableNode.myString private
Definition at line 11 of file VariableNode.java.
Referenced by tree.VariableNode.VariableNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/tree/VariableNode.java