slogo_team08: view.ColorChooser Class Reference
view.ColorChooser Class Reference
Public Member Functions
ColorChooser (Display d)
HBox formatColorSelector (String object)
void makeColorChooserPopUp (Stage stage)
Static Public Attributes
static final Integer[] SIZE_OF_COLORCHOOSER_POPUP ={400,120}
Protected Member Functions
Display getDisplay ()
Private Attributes
Color penColor
Color backgroundColor
Display disp
Detailed Description
Definition at line 13 of file ColorChooser.java.
Constructor & Destructor Documentation
view.ColorChooser.ColorChooser (Display d)
Definition at line 20 of file ColorChooser.java.
Member Function Documentation
HBox view.ColorChooser.formatColorSelector (String object)
Definition at line 25 of file ColorChooser.java.
Referenced by view.ColorChooser.makeColorChooserPopUp().
Display view.ColorChooser.getDisplay () protected
Definition at line 69 of file ColorChooser.java.
References view.ColorChooser.disp.
Referenced by view.ButtonBar.ButtonBar().
void view.ColorChooser.makeColorChooserPopUp (Stage stage)
Definition at line 52 of file ColorChooser.java.
References view.ColorChooser.formatColorSelector().
Referenced by view.ButtonBar.makeButtonBar().
Member Data Documentation
Color view.ColorChooser.backgroundColor private
Definition at line 18 of file ColorChooser.java.
Display view.ColorChooser.disp private
Definition at line 19 of file ColorChooser.java.
Referenced by view.ColorChooser.getDisplay().
Color view.ColorChooser.penColor private
Definition at line 17 of file ColorChooser.java.
final Integer [] view.ColorChooser.SIZE_OF_COLORCHOOSER_POPUP ={400,120} static
Definition at line 15 of file ColorChooser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/ColorChooser.java