slogo_team08: view.EnterCommands Class Reference
view.EnterCommands Class Reference
Public Member Functions
EnterCommands (PreviousCommands p)
Static Public Attributes
static final Integer[] LOCATION_OF_ENTERCOMMANDS_BOX ={100,500}
Protected Member Functions
HBox makeBox ()
TextArea init ()
void runCommand ()
Button clearHistory ()
String getHistory ()
void uploadCommand (String s)
Private Attributes
TextArea text = new TextArea()
String commandText =""
PreviousCommands prev
String myFormatText
ImportDesign upload = new ImportDesign()
Detailed Description
Definition at line 22 of file EnterCommands.java.
Constructor & Destructor Documentation
view.EnterCommands.EnterCommands (PreviousCommands p)
Definition at line 32 of file EnterCommands.java.
Member Function Documentation
Button view.EnterCommands.clearHistory () protected
Definition at line 62 of file EnterCommands.java.
References view.PreviousCommands.getTextArea().
Referenced by view.PreviousCommands.makeBox().
String view.EnterCommands.getHistory () protected
Definition at line 73 of file EnterCommands.java.
Referenced by view.CreateDesign.saveFile().
TextArea view.EnterCommands.init () protected
Definition at line 47 of file EnterCommands.java.
References view.EnterCommands.text.
Referenced by view.EnterCommands.runCommand().
HBox view.EnterCommands.makeBox () protected
Definition at line 36 of file EnterCommands.java.
References view.EnterCommands.runCommand().
Referenced by view.View.start().
void view.EnterCommands.runCommand () protected
Definition at line 51 of file EnterCommands.java.
References view.EnterCommands.init(), and view.PreviousCommands.updateTextArea().
Referenced by view.EnterCommands.makeBox().
void view.EnterCommands.uploadCommand (String s) protected
Definition at line 78 of file EnterCommands.java.
Referenced by view.ImportDesign.chooseDesign().
Member Data Documentation
String view.EnterCommands.commandText ="" private
Definition at line 27 of file EnterCommands.java.
final Integer [] view.EnterCommands.LOCATION_OF_ENTERCOMMANDS_BOX ={100,500} static
Definition at line 24 of file EnterCommands.java.
String view.EnterCommands.myFormatText private
Definition at line 29 of file EnterCommands.java.
PreviousCommands view.EnterCommands.prev private
Definition at line 28 of file EnterCommands.java.
TextArea view.EnterCommands.text = new TextArea() private
Definition at line 26 of file EnterCommands.java.
Referenced by view.EnterCommands.init().
ImportDesign view.EnterCommands.upload = new ImportDesign() private
Definition at line 30 of file EnterCommands.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/EnterCommands.java