slogo_team08: view.LanguageChooser Class Reference
view.LanguageChooser Class Reference
Public Member Functions
LanguageChooser (View v)
StringProperty getStringProperty ()
Static Public Attributes
static final Integer[] SIZE_OF_POPUP ={450,250}
Protected Member Functions
void setLanguage (Stage stage)
String getLanguage ()
Private Attributes
ComboBox< String > languageComboBox = new ComboBox<String>()
String language ="English"
View view
StringProperty languageProp =new SimpleStringProperty(language)
Detailed Description
Definition at line 15 of file LanguageChooser.java.
Constructor & Destructor Documentation
view.LanguageChooser.LanguageChooser (View v)
Definition at line 25 of file LanguageChooser.java.
Member Function Documentation
String view.LanguageChooser.getLanguage () protected
Definition at line 71 of file LanguageChooser.java.
References view.LanguageChooser.language.
StringProperty view.LanguageChooser.getStringProperty ()
Definition at line 67 of file LanguageChooser.java.
References view.LanguageChooser.languageProp.
Referenced by view.View.addModelListeners().
void view.LanguageChooser.setLanguage (Stage stage) protected
Definition at line 29 of file LanguageChooser.java.
References view.View.getModel(), and application.Model.setLanguage().
Referenced by view.ButtonBar.makeButtonBar().
Member Data Documentation
String view.LanguageChooser.language ="English" private
Definition at line 21 of file LanguageChooser.java.
Referenced by view.LanguageChooser.getLanguage().
ComboBox<String> view.LanguageChooser.languageComboBox = new ComboBox<String>() private
Definition at line 20 of file LanguageChooser.java.
StringProperty view.LanguageChooser.languageProp =new SimpleStringProperty(language) private
Definition at line 23 of file LanguageChooser.java.
Referenced by view.LanguageChooser.getStringProperty().
final Integer [] view.LanguageChooser.SIZE_OF_POPUP ={450,250} static
Definition at line 17 of file LanguageChooser.java.
View view.LanguageChooser.view private
Definition at line 22 of file LanguageChooser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/LanguageChooser.java