slogo_team08: tree.CommandNode Class Reference
tree.CommandNode Class Reference abstract
Public Member Functions
CommandNode (Model myModel, Class...myParameterArray)
List< Object > evaluate (Turtle myTurtle, List< Object > args)
int getArgNum ()
void addChild (TreeNode child)
int countVariables ()
List< VariableNode > getVariableNodes ()
Public Member Functions inherited from tree.TreeNode
abstract List< Object > evaluate (Turtle myTurtle, List< Object > args)
List< Object > evaluate ()
abstract int countVariables ()
abstract List< VariableNode > getVariableNodes ()
Protected Member Functions
abstract List< Object > function (Turtle myTurtle, List< Object > args)
List< Object > putObjectInList (Object o)
Model getModel ()
void setArgNum (int myArgNum)
List< TreeNode > getRootNodes (Object myBlockNode)
void checkParameters (List< Object > args, Class...myParameterArray)
void setParameterArray (Class...myParameterArray)
Class[] generateClassArray (Class c, int n)
List< Double > blockToDoubleList (BlockNode myBlockNode)
Private Member Functions
List< Object > evaluateTurtles (List< Turtle > myTurtles, List< Object > args)
void throwParametersException ()
Private Attributes
Model myModel
List< TreeNode > myChildren
int myArgNum
Class[] myParameterArray
Detailed Description
Definition at line 10 of file CommandNode.java.
Constructor & Destructor Documentation
tree.CommandNode.CommandNode (Model myModel, Class... myParameterArray)
Definition at line 17 of file CommandNode.java.
References tree.CommandNode.myModel, and tree.CommandNode.myParameterArray.
Member Function Documentation
void tree.CommandNode.addChild (TreeNode child)
Definition at line 82 of file CommandNode.java.
Referenced by tree.TreeBuilder.addChildren().
List<Double> tree.CommandNode.blockToDoubleList (BlockNode myBlockNode) protected
Definition at line 138 of file CommandNode.java.
References tree.CommandNode.checkParameters(), tree.CommandNode.generateClassArray(), and tree.CommandNode.getRootNodes().
Referenced by commands.Ask.function(), and commands.Tell.function().
void tree.CommandNode.checkParameters (List< Object > args, Class... myParameterArray) protected
Definition at line 111 of file CommandNode.java.
References tree.CommandNode.throwParametersException().
Referenced by tree.CommandNode.blockToDoubleList(), tree.CommandNode.evaluateTurtles(), commands.For.function(), commands.DoTimes.function(), and commands.MakeUserInstruction.getVariableList().
int tree.CommandNode.countVariables ()
Definition at line 87 of file CommandNode.java.
List<Object> tree.CommandNode.evaluate (Turtle myTurtle, List< Object > args)
Parameters
parameters collection of parameters needed to compute the given command
Returns
double result from executing the command
Definition at line 29 of file CommandNode.java.
References tree.CommandNode.evaluateTurtles(), application.TurtleList.getActiveTurtles(), and application.Model.getTurtleList().
Referenced by commands.If.evaluateCommand(), commands.Ask.function(), and application.Model.update().
List<Object> tree.CommandNode.evaluateTurtles (List< Turtle > myTurtles, List< Object > args) private
Definition at line 39 of file CommandNode.java.
References tree.CommandNode.checkParameters().
Referenced by tree.CommandNode.evaluate().
abstract List<Object> tree.CommandNode.function (Turtle myTurtle, List< Object > args) abstract protected
Class [] tree.CommandNode.generateClassArray (Class c, int n) protected
Definition at line 126 of file CommandNode.java.
Referenced by tree.CommandNode.blockToDoubleList(), and commands.MakeUserInstruction.getVariableList().
int tree.CommandNode.getArgNum ()
Definition at line 64 of file CommandNode.java.
References tree.CommandNode.myArgNum.
Referenced by tree.TreeBuilder.addChildren(), and tree.EvaluatorNode.generateParameterArray().
Model tree.CommandNode.getModel () protected
Definition at line 60 of file CommandNode.java.
References tree.CommandNode.myModel.
Referenced by commands.Forward.advanceTurtle(), commands.If.evaluateCommand(), commands.ClearStamp.function(), commands.SetPenSize.function(), commands.SetPenColor.function(), commands.SetPallet.function(), commands.SetBackground.function(), commands.PenColor.function(), commands.Turtles.function(), commands.MakeVariable.function(), commands.Backward.function(), commands.ID.function(), commands.ClearScreen.function(), commands.Tell.function(), commands.Ask.function(), commands.MakeUserInstruction.function(), and commands.DoTimes.runForLoop().
List<TreeNode> tree.CommandNode.getRootNodes (Object myBlockNode) protected
Definition at line 72 of file CommandNode.java.
References tree.TreeNode.evaluate(), and tree.CommandNode.putObjectInList().
Referenced by tree.CommandNode.blockToDoubleList(), commands.If.evaluateCommand(), commands.For.function(), commands.Ask.function(), commands.DoTimes.function(), commands.MakeUserInstruction.function(), and commands.DoTimes.runForLoop().
List<VariableNode> tree.CommandNode.getVariableNodes ()
Definition at line 96 of file CommandNode.java.
List<Object> tree.CommandNode.putObjectInList (Object o) protected
Definition at line 54 of file CommandNode.java.
Referenced by commands.And.function(), commands.ArcTangent.function(), commands.YCoordinate.function(), commands.XCoordinate.function(), commands.Turtles.function(), commands.ClearScreen.function(), commands.Tangent.function(), commands.Sum.function(), commands.Pi.function(), commands.Sine.function(), commands.ShowTurtle.function(), commands.Shape.function(), commands.SetTowards.function(), commands.Power.function(), commands.Product.function(), commands.SetPenSize.function(), commands.SetPenColor.function(), commands.SetPallet.function(), commands.Quotient.function(), commands.SetBackground.function(), commands.Right.function(), commands.Equal.function(), commands.IsPenDown.function(), commands.Remainder.function(), commands.IsShowing.function(), commands.ClearStamp.function(), commands.Left.function(), commands.PenUp.function(), commands.PenDown.function(), commands.PenColor.function(), commands.Or.function(), commands.NotEqual.function(), commands.Not.function(), commands.Stamp.function(), commands.Minus.function(), commands.MakeVariable.function(), commands.SetShape.function(), commands.SetHeading.function(), commands.LessThan.function(), commands.GreaterThan.function(), commands.Backward.function(), commands.Cosine.function(), commands.Heading.function(), commands.ID.function(), commands.Home.function(), commands.HideTurtle.function(), commands.Difference.function(), commands.SetPosition.function(), commands.IfElse.function(), commands.NaturalLog.function(), commands.Forward.function(), commands.Random.function(), commands.If.function(), commands.Tell.function(), commands.MakeUserInstruction.function(), tree.CommandNode.getRootNodes(), and commands.DoTimes.runForLoop().
void tree.CommandNode.setArgNum (int myArgNum) protected
Definition at line 68 of file CommandNode.java.
References tree.CommandNode.myArgNum.
Referenced by tree.EvaluatorNode.EvaluatorNode().
void tree.CommandNode.setParameterArray (Class... myParameterArray) protected
Definition at line 122 of file CommandNode.java.
References tree.CommandNode.myParameterArray.
Referenced by tree.EvaluatorNode.generateParameterArray(), commands.IfElse.IfElse(), and commands.Repeat.Repeat().
void tree.CommandNode.throwParametersException () private
Definition at line 134 of file CommandNode.java.
Referenced by tree.CommandNode.checkParameters().
Member Data Documentation
int tree.CommandNode.myArgNum private
Definition at line 14 of file CommandNode.java.
Referenced by tree.CommandNode.getArgNum(), and tree.CommandNode.setArgNum().
List<TreeNode> tree.CommandNode.myChildren private
Definition at line 13 of file CommandNode.java.
Model tree.CommandNode.myModel private
Definition at line 12 of file CommandNode.java.
Referenced by tree.CommandNode.CommandNode(), and tree.CommandNode.getModel().
Class [] tree.CommandNode.myParameterArray private
Definition at line 15 of file CommandNode.java.
Referenced by tree.CommandNode.CommandNode(), and tree.CommandNode.setParameterArray().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/tree/CommandNode.java