slogo_team08: application.TurtleList Class Reference
application.TurtleList Class Reference
Public Member Functions
TurtleList ()
List< Turtle > getActiveTurtles ()
double getID (Turtle t)
Turtle getTurtle (double id)
List< Turtle > getTurtles (List< Double > turtleIDList)
DoubleProperty IDProperty ()
void addTurtle (double id)
void setActiveTurtles (List< Double > list)
double getTurtleCount ()
Private Member Functions
void addTurtleToList (double id, List< Turtle > turtleList)
Private Attributes
List< Turtle > myActiveList = new ArrayList<>()
Map< Turtle, Double > IDMap = new HashMap<>()
Map< Double, Turtle > TurtleMap = new HashMap<>()
DoubleProperty newID = new SimpleDoubleProperty()
Detailed Description
Definition at line 12 of file TurtleList.java.
Constructor & Destructor Documentation
application.TurtleList.TurtleList ()
Definition at line 19 of file TurtleList.java.
References application.TurtleList.addTurtle().
Member Function Documentation
void application.TurtleList.addTurtle (double id)
Definition at line 53 of file TurtleList.java.
Referenced by application.TurtleList.setActiveTurtles(), and application.TurtleList.TurtleList().
void application.TurtleList.addTurtleToList (double id, List< Turtle > turtleList) private
Definition at line 41 of file TurtleList.java.
Referenced by application.TurtleList.getTurtles().
List<Turtle> application.TurtleList.getActiveTurtles ()
Definition at line 23 of file TurtleList.java.
References application.TurtleList.myActiveList.
Referenced by view.TurtleState.attrib(), and tree.CommandNode.evaluate().
double application.TurtleList.getID (Turtle t)
Definition at line 27 of file TurtleList.java.
Turtle application.TurtleList.getTurtle (double id)
Definition at line 31 of file TurtleList.java.
Referenced by view.View.addModelListeners(), and view.View.start().
double application.TurtleList.getTurtleCount ()
Definition at line 70 of file TurtleList.java.
List<Turtle> application.TurtleList.getTurtles (List< Double > turtleIDList)
Definition at line 35 of file TurtleList.java.
References application.TurtleList.addTurtleToList().
Referenced by commands.Ask.function().
DoubleProperty application.TurtleList.IDProperty ()
Definition at line 49 of file TurtleList.java.
References application.TurtleList.newID.
Referenced by view.View.addModelListeners().
void application.TurtleList.setActiveTurtles (List< Double > list)
Definition at line 63 of file TurtleList.java.
References application.TurtleList.addTurtle().
Referenced by commands.Tell.function().
Member Data Documentation
Map<Turtle, Double> application.TurtleList.IDMap = new HashMap<>() private
Definition at line 15 of file TurtleList.java.
List<Turtle> application.TurtleList.myActiveList = new ArrayList<>() private
Definition at line 14 of file TurtleList.java.
Referenced by application.TurtleList.getActiveTurtles().
DoubleProperty application.TurtleList.newID = new SimpleDoubleProperty() private
Definition at line 17 of file TurtleList.java.
Referenced by application.TurtleList.IDProperty().
Map<Double, Turtle> application.TurtleList.TurtleMap = new HashMap<>() private
Definition at line 16 of file TurtleList.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/application/TurtleList.java