slogo_team08: syntax.ListHandler Class Reference
syntax.ListHandler Class Reference abstract
Public Member Functions
ListHandler (Model myModel, Parser myParser, List< Entry< String, Pattern >> myCommandPatterns)
abstract boolean handle (String s, Iterator< String > iter, List< TreeNode > nodeList) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException
Public Member Functions inherited from syntax.SyntaxHandler
SyntaxHandler (Model myModel, Parser myParser, List< Map.Entry< String, Pattern >> myCommandPatterns)
abstract boolean handle (String s, Iterator< String > iter, List< TreeNode > nodeList) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, SecurityException, ClassNotFoundException
Static Protected Member Functions
static int getListDepthCount ()
static void setListDepthCount (int listDepthCount)
Static Private Attributes
static int listDepthCount = 0
Additional Inherited Members
Protected Attributes inherited from syntax.SyntaxHandler
Model myModel
Parser myParser
List< Map.Entry< String, Pattern > > myCommandPatterns
Detailed Description
Definition at line 13 of file ListHandler.java.
Constructor & Destructor Documentation
syntax.ListHandler.ListHandler (Model myModel, Parser myParser, List< Entry< String, Pattern >> myCommandPatterns)
Definition at line 16 of file ListHandler.java.
References syntax.SyntaxHandler.myCommandPatterns.
Member Function Documentation
static int syntax.ListHandler.getListDepthCount () static protected
Definition at line 21 of file ListHandler.java.
References syntax.ListHandler.listDepthCount.
Referenced by syntax.ListEndHandler.handle(), and syntax.ListStartHandler.handle().
abstract boolean syntax.ListHandler.handle (String s, Iterator< String > iter, List< TreeNode > nodeList) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException abstract
static void syntax.ListHandler.setListDepthCount (int listDepthCount) static protected
Definition at line 25 of file ListHandler.java.
References syntax.ListHandler.listDepthCount.
Referenced by syntax.ListEndHandler.handle(), and syntax.ListStartHandler.handle().
Member Data Documentation
int syntax.ListHandler.listDepthCount = 0 static private
Definition at line 14 of file ListHandler.java.
Referenced by syntax.ListHandler.getListDepthCount(), and syntax.ListHandler.setListDepthCount().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/syntax/ListHandler.java