slogo_team08: view.Display Class Reference
view.Display Class Reference
Static Public Attributes
static final int SIZE_OF_TURTLE =30
static final int OFFSET =375/2
static final Integer[] LOCATION_OF_DISPLAY ={200,100}
Protected Member Functions
Group makeDisplay (int height, int width, Turtle t)
ImageView addTurtle (int xLocation, int yLocation, Turtle t)
ImageView updateTurtleImage ()
void updateMap (Turtle t, ImageView w)
void addToRoot (Node n)
Map< Turtle, ImageView > getMap ()
void updateTurtleLocation (double newX, double newY, Turtle t)
void updateTurtleHeading (Number newValue, Turtle t)
void updateTurtleShowing (boolean show, Turtle t)
Line drawLines (double startX, double startY, double endX, double endY)
void setVisibility (boolean pen)
void setBackgroundFill (Color c)
void setLineFill (Color c)
Group getRoot ()
Private Attributes
Group root
Rectangle initial
Color penColor
ImageView turtleImage =new ImageView()
Turtle myTurtle
boolean penDown
double xLoc
double yLoc
Map< Turtle, ImageView > imageMap = new HashMap<Turtle, ImageView>()
Detailed Description
Definition at line 19 of file Display.java.
Member Function Documentation
void view.Display.addToRoot (Node n) protected
Definition at line 65 of file Display.java.
Referenced by view.View.addModelListeners().
ImageView view.Display.addTurtle (int xLocation, int yLocation, Turtle t) protected
Definition at line 46 of file Display.java.
Referenced by view.View.addModelListeners(), and view.Display.makeDisplay().
Line view.Display.drawLines (double startX, double startY, double endX, double endY) protected
Definition at line 85 of file Display.java.
Referenced by view.Display.updateTurtleLocation().
Map<Turtle,ImageView> view.Display.getMap () protected
Definition at line 69 of file Display.java.
References view.Display.imageMap.
Referenced by view.View.addModelListeners().
Group view.Display.getRoot () protected
Definition at line 106 of file Display.java.
References view.Display.root.
Referenced by view.View.addModelListeners().
Group view.Display.makeDisplay (int height, int width, Turtle t) protected
Definition at line 33 of file Display.java.
References view.Display.addTurtle(), and view.Display.root.
Referenced by view.View.addModelListeners(), and view.View.start().
void view.Display.setBackgroundFill (Color c) protected
Definition at line 99 of file Display.java.
void view.Display.setLineFill (Color c) protected
Definition at line 102 of file Display.java.
void view.Display.setVisibility (boolean pen) protected
Definition at line 96 of file Display.java.
Referenced by view.View.addTurtleListeners().
void view.Display.updateMap (Turtle t, ImageView w) protected
Definition at line 61 of file Display.java.
Referenced by view.View.addModelListeners().
void view.Display.updateTurtleHeading (Number newValue, Turtle t) protected
Definition at line 79 of file Display.java.
Referenced by view.View.addTurtleListeners().
ImageView view.Display.updateTurtleImage () protected
Definition at line 57 of file Display.java.
References view.Display.turtleImage.
Referenced by view.ImageChooser.openFile().
void view.Display.updateTurtleLocation (double newX, double newY, Turtle t) protected
Definition at line 73 of file Display.java.
References view.Display.drawLines().
Referenced by view.View.addTurtleListeners().
void view.Display.updateTurtleShowing (boolean show, Turtle t) protected
Definition at line 82 of file Display.java.
Referenced by view.View.addTurtleListeners().
Member Data Documentation
Map<Turtle, ImageView> view.Display.imageMap = new HashMap<Turtle, ImageView>() private
Definition at line 32 of file Display.java.
Referenced by view.Display.getMap().
Rectangle view.Display.initial private
Definition at line 24 of file Display.java.
final Integer [] view.Display.LOCATION_OF_DISPLAY ={200,100} static
Definition at line 22 of file Display.java.
Turtle view.Display.myTurtle private
Definition at line 28 of file Display.java.
final int view.Display.OFFSET =375/2 static
Definition at line 21 of file Display.java.
Color view.Display.penColor private
Definition at line 26 of file Display.java.
boolean view.Display.penDown private
Definition at line 29 of file Display.java.
Group view.Display.root private
Definition at line 23 of file Display.java.
Referenced by view.Display.getRoot(), and view.Display.makeDisplay().
final int view.Display.SIZE_OF_TURTLE =30 static
Definition at line 20 of file Display.java.
Referenced by view.ImageChooser.openFile().
ImageView view.Display.turtleImage =new ImageView() private
Definition at line 27 of file Display.java.
Referenced by view.Display.updateTurtleImage().
double view.Display.xLoc private
Definition at line 30 of file Display.java.
double view.Display.yLoc private
Definition at line 31 of file Display.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/Display.java