slogo_team08: XMLParser Class Reference
XMLParser Class Reference
Public Member Functions
XMLParser (String path) throws ParserConfigurationException, SAXException, IOException
void writeXML (Parameters p) throws ParserConfigurationException, TransformerFactoryConfigurationError, TransformerException
int getIntSpec (String tag)
boolean getBoolSpec (String tag)
String getSimSpec (String tag)
String getSimType ()
HashMap< Integer, State > getStateMap ()
String getGridType ()
int[][] getGrid ()
int[] getInteractStates ()
boolean getCornerNeighbors ()
boolean getWrapAround ()
int getNeighborhoodSize ()
int getNumCellProperties ()
Private Member Functions
void setSpec (String field, String param, String tag, String value)
String gridToString (int[][] grid)
void setValue (Element e, String tag, String value)
String pullValue (Element e, String tag)
Element pullElement (NodeList n, int index)
NodeList pullField (Element e, String tag)
Private Attributes
Document myDoc
Element myRoot
Detailed Description
Definition at line 25 of file XMLParser.java.
Constructor & Destructor Documentation
XMLParser.XMLParser (String path) throws ParserConfigurationException, SAXException, IOException
Instantiates the XMLParser class, which reads from and writes to XML files
Parameters
path the path from which to read the XML
Definition at line 35 of file XMLParser.java.
References pullElement().
Member Function Documentation
boolean XMLParser.getBoolSpec (String tag)
gets a SimSpec and returns it as an boolean
Parameters
tag name of SimSpec
Returns
desired boolean value
Definition at line 187 of file XMLParser.java.
References getSimSpec().
Referenced by getCornerNeighbors(), and getWrapAround().
boolean XMLParser.getCornerNeighbors ()
Definition at line 286 of file XMLParser.java.
References getBoolSpec().
int [][] XMLParser.getGrid ()
gets a grid of state locations
Returns
grid
Definition at line 251 of file XMLParser.java.
References pullValue().
String XMLParser.getGridType ()
Definition at line 242 of file XMLParser.java.
References pullValue().
int [] XMLParser.getInteractStates ()
gets an array of integers representing states that the user can interact with
Returns
array
Definition at line 272 of file XMLParser.java.
References getSimSpec().
int XMLParser.getIntSpec (String tag)
gets a SimSpec and returns it as an int
Parameters
tag name of SimSpec
Returns
desired int value
Definition at line 176 of file XMLParser.java.
References getSimSpec().
Referenced by getNeighborhoodSize(), and getNumCellProperties().
int XMLParser.getNeighborhoodSize ()
Definition at line 294 of file XMLParser.java.
References getIntSpec().
int XMLParser.getNumCellProperties ()
Definition at line 298 of file XMLParser.java.
References getIntSpec().
String XMLParser.getSimSpec (String tag)
gets a SimSpec, a generic parameter in the SimSpecs field, and returns it
Parameters
tag name of SimSpec
Returns
SimSpec
Definition at line 197 of file XMLParser.java.
References pullField(), and pullValue().
Referenced by getBoolSpec(), getInteractStates(), and getIntSpec().
String XMLParser.getSimType ()
gets the type of simulation
Returns
type of simulation
Definition at line 217 of file XMLParser.java.
References pullValue().
Referenced by writeXML().
HashMap<Integer, State> XMLParser.getStateMap ()
gets a map of state indices and maps them to their respective State objects
Returns
map
Definition at line 226 of file XMLParser.java.
References pullField(), and pullValue().
boolean XMLParser.getWrapAround ()
Definition at line 290 of file XMLParser.java.
References getBoolSpec().
String XMLParser.gridToString (int grid[][]) private
converts a grid to a String for writing to file
Parameters
grid an int[][] specifying states at coordinates
Returns
a String representation of the grid
Definition at line 110 of file XMLParser.java.
Referenced by writeXML().
Element XMLParser.pullElement (NodeList n, int index) private
gets a Node at index and casts to Element for use in queries
Parameters
n NodeList of child elements
index index in the NodeList
Returns
Element casted from Node
Definition at line 155 of file XMLParser.java.
Referenced by XMLParser().
NodeList XMLParser.pullField (Element e, String tag) private
gets a NodeList of children of the field named tag
Parameters
e root element
tag name of the field
Returns
NodeList
Definition at line 166 of file XMLParser.java.
Referenced by getSimSpec(), getStateMap(), pullValue(), setSpec(), and setValue().
String XMLParser.pullValue (Element e, String tag) private
pulls a free parameter by matching the parameter name with tag
Parameters
e the root element
tag the id to check
value the value to set
Returns
the value of the parameter
Definition at line 144 of file XMLParser.java.
References pullField().
Referenced by getGrid(), getGridType(), getSimSpec(), getSimType(), and getStateMap().
void XMLParser.setSpec (String field, String param, String tag, String value) private
sets a parameter contained within a field by matching the element ID with tag
Parameters
field the field name
param the parameter name
tag the id to check
value the value to set
Definition at line 90 of file XMLParser.java.
References pullField(), and setValue().
Referenced by writeXML().
void XMLParser.setValue (Element e, String tag, String value) private
sets a free parameter by matching the parameter name with tag
Parameters
e the root element
tag the id to check
value the value to set
Definition at line 132 of file XMLParser.java.
References pullField().
Referenced by setSpec(), and writeXML().
void XMLParser.writeXML (Parameters p) throws ParserConfigurationException, TransformerFactoryConfigurationError, TransformerException
Using the original parsed xml as a template, this writes a new xml file with parameter changes specified in p
Parameters
p a Parameters object, which contains parameter values to alter
Definition at line 49 of file XMLParser.java.
References getSimType(), gridToString(), setSpec(), and setValue().
Member Data Documentation
Document XMLParser.myDoc private
Definition at line 27 of file XMLParser.java.
Element XMLParser.myRoot private
Definition at line 28 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/XMLParser.java