slogo_team08: application.Parser Class Reference
application.Parser Class Reference
Public Member Functions
Parser (Model myModel)
void updateCommandPatterns ()
CommandNode parse (String input) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException
TreeNode parseIterator (Iterator< String > iter) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException
Private Attributes
List< Map.Entry< String, Pattern > > myCommandPatterns
List< Map.Entry< String, Pattern > > mySyntaxPatterns
Model myModel
TreeBuilder myTreeBuilder
Detailed Description
Definition at line 19 of file Parser.java.
Constructor & Destructor Documentation
application.Parser.Parser (Model myModel)
Definition at line 25 of file Parser.java.
References application.Model.getLanguage(), application.PatternMatcher.makePatterns(), and application.Parser.myModel.
Member Function Documentation
CommandNode application.Parser.parse (String input) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException
Definition at line 36 of file Parser.java.
References application.Parser.parseIterator().
Referenced by application.Model.update().
TreeNode application.Parser.parseIterator (Iterator< String > iter) throws InstantiationException, IllegalAccessException, InvocationTargetException, ClassNotFoundException
Definition at line 40 of file Parser.java.
References tree.TreeBuilder.build(), application.PatternMatcher.checkForMatch(), and syntax.SyntaxHandler.handle().
Referenced by syntax.GroupStartHandler.handle(), syntax.ListStartHandler.handle(), and application.Parser.parse().
void application.Parser.updateCommandPatterns ()
Definition at line 32 of file Parser.java.
References application.Model.getLanguage(), and application.PatternMatcher.makePatterns().
Referenced by application.Model.updateCommandPatterns().
Member Data Documentation
List<Map.Entry<String, Pattern> > application.Parser.myCommandPatterns private
Definition at line 20 of file Parser.java.
Model application.Parser.myModel private
Definition at line 22 of file Parser.java.
Referenced by application.Parser.Parser().
List<Map.Entry<String, Pattern> > application.Parser.mySyntaxPatterns private
Definition at line 21 of file Parser.java.
TreeBuilder application.Parser.myTreeBuilder private
Definition at line 23 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/application/Parser.java