slogo_team08: view.PreviousCommands Class Reference
view.PreviousCommands Class Reference
Protected Member Functions
TextArea getTextArea ()
void updateTextArea (String moreText)
Private Attributes
TextArea text = new TextArea()
EnterCommands enter =new EnterCommands(this)
Static Private Attributes
static final Integer[] SIZE_OF_PREVIOUSCOMMANDS_BOX ={200,350}
Detailed Description
Definition at line 13 of file PreviousCommands.java.
Member Function Documentation
TextArea view.PreviousCommands.getTextArea () protected
Definition at line 22 of file PreviousCommands.java.
References view.PreviousCommands.text.
Referenced by view.EnterCommands.getHistory(), and view.View.start().
void view.PreviousCommands.updateTextArea (String moreText) protected
Definition at line 28 of file PreviousCommands.java.
Referenced by view.EnterCommands.runCommand().
Member Data Documentation
EnterCommands view.PreviousCommands.enter =new EnterCommands(this) private
Definition at line 20 of file PreviousCommands.java.
final Integer [] view.PreviousCommands.SIZE_OF_PREVIOUSCOMMANDS_BOX ={200,350} static private
Definition at line 16 of file PreviousCommands.java.
TextArea view.PreviousCommands.text = new TextArea() private
Definition at line 19 of file PreviousCommands.java.
Referenced by view.PreviousCommands.getTextArea().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/view/PreviousCommands.java