slogo_team08: application.Wrapper Class Reference
application.Wrapper Class Reference
Public Member Functions
void makeNewWindow (Model myModel, View myView)
Static Public Member Functions
static synchronized Wrapper getInstance ()
Private Attributes
List< Pair< Model, View > > listOfWindows =new ArrayList<Pair<Model,View>>()
Static Private Attributes
static Wrapper instance
Detailed Description
Definition at line 11 of file Wrapper.java.
Member Function Documentation
static synchronized Wrapper application.Wrapper.getInstance () static
Definition at line 20 of file Wrapper.java.
References application.Wrapper.instance.
Referenced by application.Main.start().
void application.Wrapper.makeNewWindow (Model myModel, View myView)
Definition at line 29 of file Wrapper.java.
References view.View.addModelListeners(), and view.View.start().
Referenced by application.Main.start().
Member Data Documentation
Wrapper application.Wrapper.instance static private
Definition at line 13 of file Wrapper.java.
Referenced by application.Wrapper.getInstance().
List<Pair<Model,View> > application.Wrapper.listOfWindows =new ArrayList<Pair<Model,View>>() private
Definition at line 14 of file Wrapper.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team08/repository/src/application/Wrapper.java